# Generated by Django 5.1.7 on 2025-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField(verbose_name='Полное имя')),
                ('Age', models.IntegerField(verbose_name='Возраст')),
                ('Profession', models.TextField(verbose_name='Профессия')),
                ('Image', models.ImageField(upload_to='photo/%Y/%m/%d')),
            ],
        ),
    ]
