# Generated by Django 5.1.7 on 2025-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=80, verbose_name='Название')),
                ('About', models.TextField(verbose_name='Описание')),
                ('ProductImage', models.ImageField(upload_to='photo/%Y/%m/%d')),
            ],
        ),
    ]
